"""empty message

Revision ID: 362163de1718
Revises: 4ffce97dcb57
Create Date: 2023-08-14 09:13:21.458134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "362163de1718"
down_revision = "4ffce97dcb57"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column(
            "total_amount",
            existing_type=sa.REAL(),
            type_=sa.Float(precision=10, asdecimal=2),
            existing_nullable=True,
        )

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.REAL(),
            type_=sa.Float(precision=10, asdecimal=2),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.Float(precision=10, asdecimal=2),
            type_=sa.REAL(),
            existing_nullable=True,
        )

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column(
            "total_amount",
            existing_type=sa.Float(precision=10, asdecimal=2),
            type_=sa.REAL(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
