name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pytest
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Pytest summary
      # You may pin to the exact commit or the version.
      # uses: dariocurr/pytest-summary@a5a006eee4e77f75c1502b8771a6fe64bd133fcf
      uses: dariocurr/pytest-summary@v2
      #with:
        # The pytest extensions to install along pytest
        #extensions: # optional
        # The pytest options
        #options: # optional
        # The path to the output file to create
        #output: # optional
        # The path to the folder containing the tests
        #paths: # optional, default is tests
        # Which tests have to be shown in the summary
        #show: # optional
